/*
LeetCode
389. Find the Difference
You are given two strings s and t.
String t is generated by random 
shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

*/
#include<iostream>
#include<vector>
#include<algorithm>
using namespace std;


 char findTheDifference(string s, string t) {
        int s1=0;
        int s2=0;
        sort(s.begin(),s.end());
        sort(t.begin(),t.end());
        //char c;
        for(int i=0;s[i]!='\0';i++)
        {
            s1+=s[i];
        }
        for(int j=0;t[j]!='\0';j++)
        {
            s2+=t[j];
        }
       // c=s2-s1;
        return s2-s1;
        
    }

     int main()
{
    string s;
    cout<<"enter the string s"<<endl;
    getline (cin, s);
     string t;
    cout<<"enter the string t"<<endl;
    getline (cin, t);
    char result = findTheDifference(s,t);
    cout<<result;
}